[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = 
    -D VERSION_MAJOR=1
    -D VERSION_MINOR=0
    -D VERSION_PATCH=0
lib_deps = 
    https://github.com/me-no-dev/ESPAsyncWebServer.git#master
    https://github.com/me-no-dev/AsyncTCP.git#master
