[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

build_flags =
    -DAPP_NAME=\"HomeSweetHome\"

lib_deps =
    bblanchon/ArduinoJson
    robtillaart/PCF8574 @ ^0.4.3

    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer @ ^3.7.10
