[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -D VERSION_MAJOR=1
    -D VERSION_MINOR=0
    -D VERSION_PATCH=0
lib_deps = 
    ESPAsyncWebServer@^3.0.0
    AsyncTCP@^2.0.0
